config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }
  root to: "pages#home"

  resources :users, only: [:show, :edit, :update]
  resources :challenges, only: [:create, :index, :new, :update, :edit, :show, :destroy]
  resources :activities, only: [:index]
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  get "dashboard", to: "pages#dashboard", as: :user_root # creates user_root_path
  get "leaderboard", to: "pages#leaderboard"
  get "webhook", to: "pages#webhook"
  post "webhook", to: "pages#handle_activities"
  patch "/users/my_account/edit", to: "users#edit", as: "edit_my_account"

  # access the email preview at http://localhost:3000/letter_opener
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-sticky-top navbar-lewagon">
  <div class=" container-fluid">
    <%= link_to user_root_path, class: "navbar-brand" do %>
      <%= image_tag "keeprunninglogo.png" %>
    <% end %>
    <div class="d-flex">
      <button class="navbar-toggler custom-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon custom-toggler"></span>
      </button>
      <% if user_signed_in? %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto list-group-horizontal justify-content-between">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "🐆 Activities", "/activities", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "🚀 New Challenge", new_challenge_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "🥇 Leaderboard", leaderboard_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
        <li class="nav-item dropdown">
          <%= image_tag current_user.profile.profile_url.to_s, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "My Strava Profile", "https://www.strava.com/settings/profile", target: :_blank, class: "dropdown-item" %>
            <%= link_to "My Account", edit_my_account_path, class: "dropdown-item" %>
            <%= link_to "Billing", "https://billing.stripe.com/p/login/test_9AQ03W9CFaJsaU87ss", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </div>
  </div>
</div>